[package]
distribution = "2201.9.3"
org = "ballerinax"
name = "openai.images"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ['AI/Images','OpenAI','Cost/Paid','Image generation','DALL-E 3','Vendor/OpenAI']
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-openai.images"

[build-options]
observabilityIncluded = true